# MTKC POC EKS - ArgoCD App: HTTPRoutes
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: EKS Customizations (ArgoCD)
# Sync Wave: 6 (after gateway)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httproutes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/shanaka-versent/EKS-Istio-GatewayAPI-Deom.git
    targetRevision: HEAD
    path: k8s/istio
    directory:
      include: "httproutes.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
